# Generated by Django 5.2.7 on 2025-10-25 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telemetrydata',
            name='device',
            field=models.ForeignKey(blank=True, help_text='Dispositivo que enviou este registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telemetry_records', to='devices.device'),
        ),
    ]
