# Generated by Django 5.2.7 on 2025-10-25 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_alter_telemetrydata_device'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome descritivo da tarefa (ex: Ligar Relé às 7h)', max_length=255)),
                ('command_json', models.JSONField(help_text='Comando a ser enviado (JSON).')),
                ('execution_time', models.DateTimeField(blank=True, help_text='Data e hora para execução (se não for recorrente)', null=True)),
                ('is_recurrent', models.BooleanField(default=False, help_text='Se verdadeiro, será reexecutado (ex: diariamente)')),
                ('recurrence_pattern', models.CharField(blank=True, help_text='Padrão de recorrência (ex: * 7 * * * para diariamente às 7h, no formato Crontab)', max_length=50, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('EXECUTED', 'Executado'), ('FAILED', 'Falhou'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('devices', models.ManyToManyField(help_text='Dispositivos que receberão este comando', related_name='scheduled_tasks', to='devices.device')),
            ],
            options={
                'verbose_name': 'Tarefa Agendada',
                'verbose_name_plural': 'Tarefas Agendadas',
            },
        ),
    ]
