# Generated by Django 5.2.7 on 2025-10-25 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_scheduledtask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledtask',
            name='recurrence_pattern',
        ),
        migrations.AddField(
            model_name='scheduledtask',
            name='last_run_at',
            field=models.DateTimeField(blank=True, help_text='Hora da última execução bem-sucedida desta tarefa.', null=True),
        ),
        migrations.AddField(
            model_name='scheduledtask',
            name='recurrent_days',
            field=models.CharField(blank=True, help_text='Dias da semana para recorrência (ex: 1,3,5 para Seg, Qua, Sex)', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='scheduledtask',
            name='recurrent_time',
            field=models.TimeField(blank=True, help_text='Hora (HH:MM) para execução diária ou semanal (se for recorrente)', null=True),
        ),
    ]
