# Generated by Django 5.2.7 on 2025-10-25 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_remove_scheduledtask_recurrence_pattern_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledtask',
            name='recurrent_days',
            field=models.CharField(blank=True, choices=[('1', 'Segunda-feira'), ('2', 'Terça-feira'), ('3', 'Quarta-feira'), ('4', 'Quinta-feira'), ('5', 'Sexta-feira'), ('6', 'Sábado'), ('7', 'Domingo')], help_text='Dias da semana para recorrência (ex: 1,3,5 para Seg, Qua, Sex)', max_length=15, null=True),
        ),
    ]
