# Generated by Django 5.2.7 on 2025-10-26 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_alter_scheduledtask_recurrent_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledtask',
            name='recurrent_days',
            field=models.CharField(blank=True, help_text='Dias da semana para recorrência (ex: 1,3,5 para Seg, Qua, Sex)', max_length=15, null=True),
        ),
    ]
