# Generated by Django 5.2.7 on 2025-10-27 03:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0006_alter_scheduledtask_recurrent_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_id',
            field=models.CharField(db_index=True, help_text='ID único enviado pelo ESP8266 (ex: A113)', max_length=50, unique=True, verbose_name='ID do Dispositivo'),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.CharField(default='Genérico', help_text='Tipo de dispositivo (ex: Rele Iluminação, Controle Ar, Sensor Temperatura)', max_length=100, verbose_name='Tipo de Dispositivo'),
        ),
        migrations.AlterField(
            model_name='device',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='Último endereço IP conhecido do dispositivo', null=True, verbose_name='Endereço IP'),
        ),
        migrations.AlterField(
            model_name='device',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indica se o dispositivo está ativo', verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='device',
            name='last_command',
            field=models.CharField(blank=True, help_text='Confirmação do último comando executado pelo dispositivo', max_length=255, null=True, verbose_name='Último Comando'),
        ),
        migrations.AlterField(
            model_name='device',
            name='last_seen',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Registro do último check-in (POST) do dispositivo', verbose_name='Última Conexão'),
        ),
        migrations.AlterField(
            model_name='device',
            name='location',
            field=models.CharField(default='Desconhecido', help_text='Localização física do dispositivo', max_length=100, verbose_name='Localização'),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(default='Dispositivo IoT', help_text='Nome amigável para exibição na interface', max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='device',
            name='pending_command',
            field=models.JSONField(blank=True, help_text="Comando pendente no formato JSON para execução (ex: {'action': 'ligar_rele', 'target': 'rele_D1', 'value': 1})", null=True, verbose_name='Comando Pendente'),
        ),
        migrations.AlterField(
            model_name='scheduledtask',
            name='command_json',
            field=models.JSONField(help_text='Comando a ser enviado (JSON). Exemplo: {"value": 0, "action": "ligar_rele", "target": "rele_D1"}', verbose_name='Comando JSON'),
        ),
        migrations.AlterField(
            model_name='scheduledtask',
            name='devices',
            field=models.ManyToManyField(help_text='Dispositivos que receberão este comando', related_name='scheduled_tasks', to='devices.device', verbose_name='Dispositivos'),
        ),
        migrations.AlterField(
            model_name='scheduledtask',
            name='execution_time',
            field=models.DateTimeField(blank=True, help_text='Data e hora para execução (se não for recorrente)', null=True, verbose_name='Data e Hora de Execução'),
        ),
        migrations.AlterField(
            model_name='scheduledtask',
            name='is_recurrent',
            field=models.BooleanField(default=False, help_text='Se selecionado, será reexecutado nos dias e horários definidos', verbose_name='Recorrente'),
        ),
        migrations.AlterField(
            model_name='scheduledtask',
            name='last_run_at',
            field=models.DateTimeField(blank=True, help_text='Hora da última execução bem-sucedida desta tarefa.', null=True, verbose_name='Última Execução'),
        ),
        migrations.AlterField(
            model_name='scheduledtask',
            name='name',
            field=models.CharField(help_text='Nome descritivo da tarefa (ex: Ligar às 7h)', max_length=255, verbose_name='Nome da Tarefa'),
        ),
        migrations.AlterField(
            model_name='scheduledtask',
            name='recurrent_days',
            field=models.CharField(blank=True, help_text='Dias da semana para recorrência (ex: 1,3,5 para Seg, Qua, Sex)', max_length=15, null=True, verbose_name='Dias da Semana (Recorrência)'),
        ),
        migrations.AlterField(
            model_name='scheduledtask',
            name='recurrent_time',
            field=models.TimeField(blank=True, help_text='Hora (HH:MM) para execução diária ou semanal (se for recorrente)', null=True, verbose_name='Horário Recorrente'),
        ),
        migrations.AlterField(
            model_name='scheduledtask',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendente'), ('EXECUTED', 'Executado'), ('FAILED', 'Falhou'), ('CANCELLED', 'Cancelado')], default='PENDING', help_text="Para ser executada, a tarefa deve estar em 'Pendente'. Tarefas recorrentes permanecerão 'Pendente' durante o ciclo de recorrência.", max_length=50),
        ),
        migrations.AlterField(
            model_name='telemetrydata',
            name='device',
            field=models.ForeignKey(blank=True, help_text='Dispositivo que enviou este registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telemetry_records', to='devices.device', verbose_name='Dispositivo'),
        ),
        migrations.AlterField(
            model_name='telemetrydata',
            name='humidity_percent',
            field=models.FloatField(blank=True, help_text='Umidade do ar em porcentagem', null=True, verbose_name='Umidade (Porcentagem)'),
        ),
        migrations.AlterField(
            model_name='telemetrydata',
            name='last_button_action',
            field=models.CharField(blank=True, help_text='Ação local acionada por botão (se houver)', max_length=50, null=True, verbose_name='Última Ação do Botão'),
        ),
        migrations.AlterField(
            model_name='telemetrydata',
            name='raw_data',
            field=models.JSONField(blank=True, help_text='Dados JSON brutos enviados pelo dispositivo', null=True, verbose_name='Dados Brutos'),
        ),
        migrations.AlterField(
            model_name='telemetrydata',
            name='relay_state_D1',
            field=models.BooleanField(default=False, help_text='Estado do relé (True/False)', verbose_name='Estado do Relé'),
        ),
        migrations.AlterField(
            model_name='telemetrydata',
            name='temperature_celsius',
            field=models.FloatField(blank=True, help_text='Temperatura em Celsius', null=True, verbose_name='Temperatura (Celsius)'),
        ),
        migrations.AlterField(
            model_name='telemetrydata',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Timestamp do registro (quando foi recebido)', verbose_name='Data/Hora do Registro'),
        ),
    ]
